import { NextPage } from 'next';
import { useState, useEffect } from 'react';
import Head from 'next/head';

import { Product } from '../components';
import { PAGE_SETTINGS } from '../constants';
import { Styled } from '../styled';

declare global {
	interface Window {
		ShopifyBuy: any;
	}
}

const Home: NextPage = () => {
	const [ui, setUi] = useState();

	const onScriptLoad = async () => {
		if (!window || !window.ShopifyBuy) {
			window.setTimeout(() => onScriptLoad, 3000);
			return;
		}

		const client = window.ShopifyBuy.buildClient({
			domain: process.env.NEXT_PUBLIC_SHOPIFY_DOMAIN,
			storefrontAccessToken: process.env.NEXT_PUBLIC_SHOPIFY_STORE_ACCESS_TOKEN,
		});

		const ui = await window.ShopifyBuy.UI.onReady(client);

		setUi(ui);
	};

	useEffect(() => {
		onScriptLoad();
	}, []);

	return (
		<>
			<Head>
				<title>{PAGE_SETTINGS.page_title}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Product ui={ui} productId='7593553985788' />
		</>
	);
};

export default Home;
